In [5]:
import pandas as pd #pandas is an lib it contains function related to the db.

In [2]:
!pip install pandas

  Obtaining dependency information for pandas from https://files.pythonhosted.org/packages/61/11/1812ef6cbd7433ad240f72161ce5f84c4c450cede4db080365d371d29117/pandas-2.2.1-cp311-cp311-win_amd64.whl.metadata
  Obtaining dependency information for numpy<2,>=1.23.2 from https://files.pythonhosted.org/packages/3f/6b/5610004206cf7f8e7ad91c5a85a8c71b2f2f8051a0c0c4d5916b76d6cbb2/numpy-1.26.4-cp311-cp311-win_amd64.whl.metadata
     ---------------------------------------- 0.0/61.0 kB ? eta -:--:--
     -------------------- ------------------- 30.7/61.0 kB 1.4 MB/s eta 0:00:01
     -------------------------------------- 61.0/61.0 kB 819.4 kB/s eta 0:00:00
  Obtaining dependency information for tzdata>=2022.7 from https://files.pythonhosted.org/packages/65/58/f9c9e6be752e9fcb8b6a0ee9fb87e6e7a1f6bcab2cdc73f02bb7ba91ada0/tzdata-2024.1-py2.py3-none-any.whl.metadata
  Using cached tzdata-2024.1-py2.py3-none-any.whl.metadata (1.4 kB)
   ---------------------------------------- 0.0/11.6 MB ? eta -:--:-

In [7]:
dataset = pd.read_csv("Salary_Data.csv") #function read-csv calls under pd class then it passes salary_Data.csv file to the variable dataset

In [9]:
dataset #here it will load all the datas present @ dataset

YearsExperience    Salary
0               1.1   39343.0
1               1.3   46205.0
2               1.5   37731.0
3               2.0   43525.0
4               2.2   39891.0
5               2.9   56642.0
6               3.0   60150.0
7               3.2   54445.0
8               3.2   64445.0
9               3.7   57189.0
10              3.9   63218.0
11              4.0   55794.0
12              4.0   56957.0
13              4.1   57081.0
14              4.5   61111.0
15              4.9   67938.0
16              5.1   66029.0
17              5.3   83088.0
18              5.9   81363.0
19              6.0   93940.0
20              6.8   91738.0
21              7.1   98273.0
22              7.9  101302.0
23              8.2  113812.0
24              8.7  109431.0
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0

In [15]:
independent=dataset[["YearsExperience"]] #assign a single column from table with there respective variable.
independent # check the variable (i.e)load the datas inside the independent variable

YearsExperience
0               1.1
1               1.3
2               1.5
3               2.0
4               2.2
5               2.9
6               3.0
7               3.2
8               3.2
9               3.7
10              3.9
11              4.0
12              4.0
13              4.1
14              4.5
15              4.9
16              5.1
17              5.3
18              5.9
19              6.0
20              6.8
21              7.1
22              7.9
23              8.2
24              8.7
25              9.0
26              9.5
27              9.6
28             10.3
29             10.5

In [16]:
dependent=dataset[["Salary"]] #assign a single column from table with there respective variable.
dependent # check the variable (i.e)load the datas inside the dependent variable

Salary
0    39343.0
1    46205.0
2    37731.0
3    43525.0
4    39891.0
5    56642.0
6    60150.0
7    54445.0
8    64445.0
9    57189.0
10   63218.0
11   55794.0
12   56957.0
13   57081.0
14   61111.0
15   67938.0
16   66029.0
17   83088.0
18   81363.0
19   93940.0
20   91738.0
21   98273.0
22  101302.0
23  113812.0
24  109431.0
25  105582.0
26  116969.0
27  112635.0
28  122391.0
29  121872.0

In [23]:
# SPLIT TRAIN SET N TEST SET.
from sklearn.model_selection import train_test_split #in sklearn lib,under model_selection file it calls  train_test_split function.
X_train,X_test,y_train,y_test=train_test_split(independent,dependent,test_size=0.30,random_state=0) #call the imported function with its respective parameters along with train n test sets i/p and o/p variable.

In [22]:
!pip install scikit-learn

  Obtaining dependency information for scikit-learn from https://files.pythonhosted.org/packages/7b/0e/25d6b5678ed3c7e12bc94d047d0e9492e89cc78b7ea0034ac0f1cf2ff304/scikit_learn-1.4.1.post1-cp311-cp311-win_amd64.whl.metadata
  Obtaining dependency information for scipy>=1.6.0 from https://files.pythonhosted.org/packages/9a/25/5b30cb3efc9566f0ebeaeca1976150316353c17031ad7868ef46de5ab8dc/scipy-1.12.0-cp311-cp311-win_amd64.whl.metadata
     ---------------------------------------- 0.0/60.4 kB ? eta -:--:--
     ------ --------------------------------- 10.2/60.4 kB ? eta -:--:--
     ------------------- ------------------ 30.7/60.4 kB 660.6 kB/s eta 0:00:01
     -------------------------------------- 60.4/60.4 kB 534.1 kB/s eta 0:00:00
  Obtaining dependency information for joblib>=1.2.0 from https://files.pythonhosted.org/packages/10/40/d551139c85db202f1f384ba8bcf96aca2f329440a844f924c8a0040b6d02/joblib-1.3.2-py3-none-any.whl.metadata
  Obtaining dependency information for threadpoolctl>=2

In [26]:
#HOW TO PASS INPUT / LEARNING PHASE
from sklearn.linear_model import LinearRegression #through sklearn lib import linear regression file inside linear_model function.
regressor = LinearRegression() #class assigned to regressor function
regressor.fit(X_train,y_train) #calls fit function using access operator,here the values are substituted ,model created.

LinearRegression()

In [30]:
weight=regressor.coef_ #used to see weight value.
weight

array([[9360.26128619]])

In [33]:
bias=regressor.intercept_ #used to see bias value.
bias

array([26777.3913412])

In [32]:
#EVALUTING THE MODEL
y_Pred=regressor.predict(X_test) #predict data from test
from sklearn.metrics import r2_score #actual and predicted input passed to r2 
r_score = r2_score(y_test,y_Pred) #r2 value evaluted nearly to 1 good model else bad model.
r_score #load the value.

0.9740993407213511

In [35]:
# HOW TO SAVE THE MODEL
import pickle #pickle lib used to save model
filename = "finalized_model_linear.sav" #filename created for finalized model
pickle.dump(regressor,open(filename,'wb')) #model assigned to pickle.


In [36]:
#CHECK THE SAVED MODEL WHETHER IT IS WORKING PROPERLY OR NOT
loaded_model = pickle.load(open("finalized_model_linear.sav",'rb')) #load the saved model(i.e)file name just read the file.
result = loaded_model.predict([[13]]) #test with given input.
result # load the value related to given input.

C:\Users\vgrex\anaconda3\New folder\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[148460.78806172]])